### Gajadi dipake ###
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: rizkinu/consumer:1.6
          env:
          - name: ENV_SERVER_EUREKA
            value: 'http://discovery-service:8761/eureka'
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
# The port that the container is running on in the cluster